export const categories = ["Frontend", "Backend"];

export const projects = [
  {
    id: 1,
    title: "Jasper",
    description: "Noteringsapplikasjon med Markdown-støtte",
    features: [
      "Real-time sales tracking",
      "Inventory management",
      "Customer analytics",
    ],
    technologies: [
      "Next.js",
      "React",
      "TailwindCSS",
      "JavaScript",
      "Radix UI",
      "Objekt-Orientert Programmering",
    ],
    cover: "/portfolio/jasper_cover_square_0.png",
    category: "Frontend",
    externalLinks: [
      {
        type: "github",
        url: "https://github.com/username/project",
        label: "GitHub",
      },
      {
        type: "deploy",
        url: "https://project.netlify.app",
        label: "Live Demo",
      },
    ],
  },
  {
    id: 3,
    title: "WeDeliverTECH",
    description:
      "Nettbasert dashbordapplikasjon utviklet for WeDeliverTECH™s resepsjonspersonale for å administrere fraværsregistrering for ansatte og overvåking av budbiler. Systemet gir sanntids oppdateringer og varsler for å sikre effektiv kontor- og leveringshåndtering.",
    features: [
      "Inn-/utsjekk-funksjonalitet for ansatte",
      "Automatisk beregning av varighet og visning av forventet tilbakekomsttid",
      "Sanntids statusoppdateringer",
      "Varsler ved sen tilbakekomst med ansattes detaljer",
      "Integrering med API for demo-ansatte",
    ],
    technologies: [
      "HTML",
      "CSS",
      "Bootstrap",
      "JavaScript",
      "Objekt-Orientert Programmering",
    ],
    cover: "/portfolio/wdt_cover_square_0.png",
    category: "Backend",
    githubUrl: "https://github.com/mariusrundereim/bed-semester-project-1",
    deployUrl: "https://papaya-clafoutis-b998c6.netlify.app",
  },
  {
    id: 4,
    title: "Holidaze",
    description: [
      "Utvikle frontend for Holidaze, en overnattingsplattform." +
        " Designe og implementere brukervennlige grensesnitt for både kunder (booking) og administratorer (registrering og administrasjon av overnattingssteder og bookinger).",
    ],
    features: [
      "Se liste over overnattingssteder",
      "Søke og filtrere etter spesifikke overnattingssteder",
      "Se detaljer om enkelt overnattingssted (sted) basert på ID",
      "Se kalender med tilgjengelige datoer for et overnattingssted",
      "Registrere seg som kunde",
      "Lage bestillinger på overnattingssteder",
      "Se kommende bestillinger",
      "Registrere seg som vert",
      "Opprette nye overnattingssteder",
      "Oppdatere eksisterende overnattingssteder de administrerer",
      "Slette overnattingssteder de administrerer",
      "Se bestillinger for overnattingssteder de administrerer",
    ],
    technologies: ["React", "Redux", "Mantine", "JavaScript", "Noroff API"],
    cover: "/portfolio/holidaze_cover_square_0.png",
    category: "Frontend",
    githubUrl: "https://github.com/mariusrundereim/exam2-holidaze",
    deployUrl: "https://holidaze-exam2.netlify.app/",
  },
  {
    id: 5,
    title: "Bidify",
    description:
      "En auksjonsside lanserer en nettside hvor brukere kan legge ut varer til bud og by på andres varer. Nye brukere får 1000 kreditter. Kreditter oppnås ved salg og brukes til kjøp. Uregistrerte kan søke, men kun registrerte kan by.",
    features: [
      "Registrering",
      "Innlogging / Utlogging",
      "Profiloppdatering",
      "Se kreditter",
      "Opprette annonser",
      "Legge inn bud",
      "Se bud",
      "Søk gjennom annonser",
    ],
    technologies: [
      "HTML",
      "CSS",
      "TailwindCss",
      "JavaScript",
      "Cypress",
      "Jest",
      "Figma",
      "REST-API",
    ],
    cover: "/portfolio/bidify_cover_square_0.png",
    category: "Frontend",
    githubUrl: "https://github.com/mariusrundereim/marius-semester-project-2",
    deployUrl: "https://mariusrundereim.github.io/marius-semester-project-2/",
  },
  {
    id: 6,
    title: "Kaupa",
    description:
      "Online e-handelsbutikk. ferdigheter i React ved å implementere en handlekurvfunksjonalitet, til tross for begrensningen med kun en GET-metode fra API'et.",
    features: [
      "Handlekurv funksjonalitet",
      "Filtrering av produkter",
      "Form validering",
      "Omregning til NOK kroner",
    ],
    technologies: [
      "React",
      "React Router",
      "React Hook Form",
      "TypeScript",
      "Zustand",
      "MUI",
    ],
    cover: "/portfolio/kaupa_cover_square_0.png",
    category: "Frontend",
    githubUrl: "https://github.com/mariusrundereim/fed-frameworks-ca-marius",
    deployUrl: "https://brilliant-madeleine-06f016.netlify.app/",
  },
];
